name: build-windows-gui

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: install prereqs
      run: |
        sudo apt update
        sudo apt install -y \
          libevent-dev \
          libminiupnpc-dev \
          libzmq5-dev \
          libqt5gui5 \
          libqt5core5a \
          libqt5dbus5 \
          qttools5-dev \
          qttools5-dev-tools \
          libprotobuf-dev \
          protobuf-compiler \
          libqrencode-dev \
          libdb++-dev \
          g++-mingw-w64-x86-64 \
          nsis \
          libboost-all-dev
    - uses: actions/checkout@v2
    - name: build depends
      run: |
        cd depends
        make HOST=x86_64-w64-mingw32
    - name: autogen and configure
      run: |
        ./autogen.sh
        CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/ --disable-man --with-incompatible-bdb
    - name: make deploy
      run: make -deploy
